WebAppLuisMendozaSamuel/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppLuisMendozaSamuel.Data.DataAccess;
using WebAppLuisMendozaSamuel.Models.Entidades;

namespace WebAppLuisMendozaSamuel.Controllers
{
    public class ClienteController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            var da = new ClienteDA();
            var clientes = da.GetListaClientes();
            return View(clientes);
        }
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost, Authorize]
        public IActionResult Create(Cliente cliente)
        {
            cliente.idCliente = 0;
            var da = new ClienteDA();
            if (da.InsertarCliente(cliente) > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(cliente);
            }
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            var da = new ClienteDA();
            var cliente = da.GetClienteById(id);
            return View(cliente);
        }
        [HttpPost, Authorize]
        public IActionResult Edit(Cliente cliente)
        {
            var da = new ClienteDA();
            if (da.ActualizarCliente(cliente))
            {
                return RedirectToAction("index");
            }
            else
            {
                return View(cliente);
            }
        }
        [Authorize]
        public IActionResult Details(int id)
        {
            var da = new ClienteDA();
            var cliente = da.GetClienteById(id);
            return View(cliente);
        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            var da = new ClienteDA();
            var cliente = da.GetClienteById(id);
            return View(cliente);
        }
        [HttpPost, Authorize]
        public IActionResult Delete(Cliente cliente)
        {
            var da = new ClienteDA();
            if (da.EliminarCliente(cliente.idCliente)){
                return RedirectToAction("index");
            }
            else
            {
                return View(cliente);
            }
        }
    }
}

WebAppLuisMendozaSamuel/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppLuisMendozaSamuel.Data.DataAccess;
using WebAppLuisMendozaSamuel.Models.Entidades;

namespace WebAppLuisMendozaSamuel.Controllers
{
    public class CompraController : Controller
    {
        public IActionResult Index()
        {
            var da = new CompraDA();
            var compras = da.GetListaCompras();
            return View(compras);
        }
        [Authorize]
        public IActionResult Create()
        {
            var da = new ProductoDA();
            var daclientes = new ClienteDA();
            ViewBag.productos = da.GetListaProductos();
            ViewBag.clientes = daclientes.GetListaClientes();
            ViewBag.alerta = "";
            return View();
        }
        [HttpPost, Authorize]
        public IActionResult Create(Compra compra)
        {
            var auxDA = new ProductoDA();
            var productoComprado = auxDA.GetProductoById(compra.idProducto);

            if (compra.cantidad <= productoComprado.stock)
            {
                var da = new CompraDA();
                compra.precioTotal = productoComprado.precioUnitario * compra.cantidad;
                productoComprado.stock = productoComprado.stock - compra.cantidad;
                auxDA.ActualizarProducto(productoComprado);
                if (da.InsertarCompra(compra) > 0)
                {
                    return RedirectToAction("index");
                }
            }
            var daclientes = new ClienteDA();
            ViewBag.productos = auxDA.GetListaProductos();
            ViewBag.clientes = daclientes.GetListaClientes();
            ViewBag.alerta = "Se ha superado el stock máximo de "+productoComprado.stock+" unidades para el producto.";
            return View();
        }
    }
}

WebAppLuisMendozaSamuel/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppLuisMendozaSamuel.Data.DataAccess;
using WebAppLuisMendozaSamuel.Models.Entidades;

namespace WebAppLuisMendozaSamuel.Controllers
{
    public class ProductoController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            var da = new ProductoDA();
            var model = da.GetListaProductos();
            return View(model);
        }
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost, Authorize]
        public IActionResult Create(Producto producto)
        {
            producto.idProducto = 0;
            var da = new ProductoDA();
            var result = da.InsertarProducto(producto);
            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(producto);
            }
        }
        [Authorize]
        public IActionResult Details(int id)
        {
            var da = new ProductoDA();
            var producto = da.GetProductoById(id);
            return View(producto);
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            var da = new ProductoDA();
            var producto = da.GetProductoById(id);
            return View(producto);
        }
        [HttpPost, Authorize]
        public IActionResult Edit(Producto producto)
        {
            var da = new ProductoDA();
            if (da.ActualizarProducto(producto))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(producto);
            }
        }
        [Authorize]
        public IActionResult Delete(int id)
        {
            var da = new ProductoDA();
            var producto = da.GetProductoById(id);
            return View(producto);
        }
        [HttpPost, Authorize]
        public IActionResult Delete(Producto producto)
        {
            var da = new ProductoDA();
            if (da.EliminarProducto(producto.idProducto))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(producto);
            }
        }
    }
}

WebAppLuisMendozaSamuel/ViewComponents/IdiomaViewComponent.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppLuisMendozaSamuel.ViewComponents
{
    public class IdiomaViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult>
       InvokeAsync()
        {
            var idiomas = new List<SelectListItem>();
            idiomas.Add(new SelectListItem() { Value = "en-US", Text = "English" });
            idiomas.Add(new SelectListItem() { Value = "es-PE", Text = "Español" });

            var currentCulture = HttpContext.Features.Get<IRequestCultureFeature>();
            ViewBag.IdiomaSeleccionado = currentCulture.RequestCulture.UICulture.Name;
            return View(idiomas);
        }
    }
}

WebAppLuisMendozaSamuel/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inicio</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />

        <link rel="stylesheet" href="~/css/materialize-icons.css" />
        <link rel="stylesheet" href="~/css/materialize.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

        <link rel="stylesheet" href="~/css/materialize-icons.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/materialize.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Tienda</a>
            </div>
            <div class="navbar-collapse collapse row">
                <ul class="nav navbar-nav col s5">
                    <li><a asp-area="" asp-controller="Producto" asp-action="Index">@Localizer["kListaProducto"]</a></li>
                    <li><a asp-area="" asp-controller="Cliente" asp-action="Index">@Localizer["kListaCliente"]</a></li>
                    <li><a asp-area="" asp-controller="Compra" asp-action="Index">@Localizer["kListaCompra"]</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Razor">@Localizer["kRazor"]</a></li>
                </ul>


                @await Component.InvokeAsync("Idioma")
                <div class="col s4">
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebAppLuisMendozaSamuel</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script src="~/js/materialize.min.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

        <script src="~/js/materialize.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    <script>

        $(document).ready(function () {
            $('#idiomas').formSelect();
        });
    </script>
</body>
</html>